@Lab.PlatformApi_HostAddress = http://localhost:5101

GET {{Lab.PlatformApi_HostAddress}}/health

###

GET {{Lab.PlatformApi_HostAddress}}/api/devices
Accept: application/json

###

GET {{Lab.PlatformApi_HostAddress}}/api/devices?status=Online
Accept: application/json

###

GET {{Lab.PlatformApi_HostAddress}}/api/devices/LAB-DEVICE-001
Accept: application/json

###
